<?php
$this->title = "My Categories";
$this->headTitle($this->title);
?>

<br>
<div class="container">
    <p>
        <button id="add-category-btn" data-action="Add" class="btn btn-primary">Add new category</button>
    </p>
    <div class="modal" tabindex="-1" id="CategoryModal" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button id="submit-category-btn" type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>



    <table id="CategoriesTable" class="display" style="width:100%">
        <thead>
        <tr>
            <th>Name</th>
            <th></th>
        </tr>
        </thead>

    </table>
</div>