<form id="addAlbumForm">
    <div class="form-group">
        <label for="title">Title</label>
        <input name="title" type="text" class="form-control" id="title">
    </div>
    <div class="form-group">
        <label for="artist">Artist</label>
        <input name="artist" type="text" class="form-control" id="artist">
    </div>
    <div class="form-group">
        <label for="albums">Choose category</label>
        <select name="cat_id[]" class="custom-select mr-sm-2" multiple="multiple" id="categories">
            <?php foreach ($this->categories as $val) : ?>
                <option value="<?= $val->id ?>"><?= $val->name ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</form>
