<form id="addMusicForm" enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Title</label>
        <input name="title" type="text" class="form-control" id="title">
    </div>
    <div class="form-group">
        <label for="duration">duration</label>
        <input name="duration" type="text" class="form-control" id="duration">
    </div>
    <p>Price :</p>
    <span id="price_error"></span>
    <div class="form-group">
        <label for="jod">JOD</label>
        <div class="input-group mb-3">
            <input name="jod" type="text" class="form-control" id="jod">
            <div class="input-group-append">
                <span class="input-group-text" id="percentage">.00</span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="dollar">Dollar</label>
        <div class="input-group mb-3">
            <input name="dollar" type="text" class="form-control" id="dollar">
            <div class="input-group-append">
                <span class="input-group-text" id="percentage">.00</span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="euro">Euro</label>
        <div class="input-group mb-3">
            <input name="euro" type="text" class="form-control" id="euro">
            <div class="input-group-append">
                <span class="input-group-text" id="percentage">.00</span>
            </div>
        </div>

    </div>
    <div class="form-group">
        <label for="discount">Discount</label>
        <div class="input-group mb-3">
            <input name="discount" type="text" class="form-control" id="discount" aria-describedby="percentage">
            <div class="input-group-append">
                <span class="input-group-text" id="percentage">%</span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="start_date">Discount start date</label>
        <input name="start_date" type="text" class="form-control" id="start_date">
    </div>
    <div class="form-group">
        <label for="end_date">Discount end date</label>
        <input name="end_date" type="text" class="form-control" id="end_date">
    </div>
    <div class="form-group">
        <label for="file">MP3 file</label>
        <input name="file" type="file" class="form-control" id="file" accept=".mp3">
    </div>
    <input name="album_id" type="hidden" id="album_id" value="<?= $this->music; ?>">
</form>
