<form id="editMusicForm" enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Title</label>
        <input name="title" type="text" class="form-control" id="title" value="<?= $this->music['title'] ;?>">
    </div>
    <div class="form-group">
        <label for="duration">duration</label>
        <input name="duration" type="text" class="form-control" id="duration" value="<?= $this->music['duration'] ;?>">
    </div>
    <p>Price :</p>
    <div class="form-group">
        <label for="jod">JOD</label>
        <div class="input-group mb-3">
            <input name="jod" type="text" class="form-control" id="jod" value="<?= $this->music['price_jod']; ?>">
            <div class="input-group-append">
                <span class="input-group-text" id="percentage">.00</span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="dollar">Dollar</label>
        <div class="input-group mb-3">
            <input name="dollar" type="text" class="form-control" id="dollar" value="<?= $this->music['price_dollar']; ?>">
            <div class="input-group-append">
                <span class="input-group-text" id="percentage">.00</span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="euro">Euro</label>
        <div class="input-group mb-3">
            <input name="euro" type="text" class="form-control" id="euro" value="<?= $this->music['price_euro']; ?>">
            <div class="input-group-append">
                <span class="input-group-text" id="percentage">.00</span>
            </div>
        </div>

    </div>
    <div class="form-group">
        <label for="discount">Discount</label>
        <div class="input-group mb-3">
            <input name="discount" type="text" class="form-control" id="discount"  value="<?= $this->music['discount']*100; ?>">
            <div class="input-group-append">
                <span class="input-group-text">%</span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="start_date">start date</label>
        <input name="start_date" type="text" class="form-control" id="start_date" value="<?= $this->music['start_date']; ?>">
    </div>
    <div class="form-group">
        <label for="end_date">end date</label>
        <input name="end_date" type="text" class="form-control" id="end_date" value="<?= $this->music['end_date']; ?>">
    </div>
    <div class="form-group">
        <label for="file">MP3 file</label>
        <input name="file" type="file" class="form-control" id="file" accept=".mp3">
        <input name="album_id" type="hidden"  id="album_id" value="<?= $this->music['album_id'] ;?>">
        <input name="music_id" type="hidden"  id="music_id" value="<?= $this->music['id'] ;?>">
    </div>

</form>
