<form id="editAlbumForm">
    <div class="form-group">
        <label for="title">Title</label>
        <input name="title" type="text" class="form-control" id="title" value="<?= $this->album['title']; ?>">
    </div>
    <div class="form-group">
        <label for="artist">Artist</label>
        <input name="artist" type="text" class="form-control" id="artist" value="<?= $this->album['artist']; ?>">
        <input type="hidden" name="id" id="id" value="<?= $this->album['id']; ?>">
    </div>

    <div class="form-group">
        <label for="albums">Choose category</label>
        <select name="cat_id[]" class="custom-select mr-sm-2" multiple="multiple" id="categories">

            <?php
            $selected = array();
            foreach ($this->category as $selected_categories) :
                array_push($selected, $selected_categories->category_id);

            endforeach; ?>

            <?php foreach ($this->categories as $general_categories) : ?>


                <option value="<?= $general_categories->id ?>"
                        <?php if (in_array($general_categories->id, $selected)): ?>selected
                    <?php endif; ?>><?= $general_categories->name ?></option>


            <?php endforeach; ?>


        </select>
    </div>


</form>
<?php
/*  */
?>