<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>

<div class="container">
    <p>
        <button id="add-album-btn" data-name="Add" class="btn btn-primary">Add new album</button>
    </p>
    <div class="modal" style="width:100%;" tabindex="-1" id="AlbumModal" role="dialog">
        <div class="modal-dialog modal-lg" style="width:100%;" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button id="submit-album-btn" type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-1" id="MusicModal" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button id="submit-music-btn" type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>


    <table id="AlbumTable" class="display" style="width:100%">
        <thead>
        <tr>
            <th>Title</th>
            <th>Artist</th>
            <th>Category</th>
            <th></th>
        </tr>
        </thead>

    </table>
</div>
