<button id="add-music-btn" data-name="Add" data-album_id="<?= $this->album; ?>" class="btn btn-primary">Add new music
</button>
<br><br>
<table id="MusicTable" class="display">
    <thead>
    <tr>
        <th>Title</th>
        <th>Duration</th>
        <th>Discount</th>
        <th>Remaining</th>
        <th>JOD</th>
        <th>Dollar</th>
        <th>Euro</th>
        <th></th>
    </tr>
    </thead>

</table>
